// Writes prisma/postgres/schema.prisma from prisma/schema.prisma, switching only the provider.
// Local development uses SQLite; production (Render) uses PostgreSQL. Run after any schema change,
// then create a migration with: npm run db:pg-migration -- <name>
import { readFileSync, writeFileSync } from "node:fs";

const src = readFileSync("prisma/schema.prisma", "utf8");
const out = src.replace(/provider\s*=\s*"sqlite"/, 'provider = "postgresql"');
if (out === src) throw new Error('Could not find provider = "sqlite" in prisma/schema.prisma');
writeFileSync(
  "prisma/postgres/schema.prisma",
  "// GENERATED by scripts/pg-schema.ts from prisma/schema.prisma. Do not edit by hand.\n" + out,
);
console.log("Wrote prisma/postgres/schema.prisma");
